basePath: /
host: https://aryka.herokuapp.com/
info:
  contact:
    email: arykaanisap22@gmail.com
    name: https://github.com/ArykaAnisaP
  description: This is a sample swagger server
  title: TES SWAG
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
